"""integration + notification wiring

Revision ID: 61147419395c
Revises: 2794f40e7c2d
Create Date: 2026-06-13 23:32:59.629508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61147419395c'
down_revision: Union[str, Sequence[str], None] = '2794f40e7c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Nowe wartości enuma notificationtype dodane przy scaleniu modułu notification.
NEW_NOTIFICATION_TYPES = ("TASK_UPDATED", "PR_CREATED", "PR_REVIEWED", "CHAT_MESSAGE")


def upgrade() -> None:
    """Upgrade schema."""
    # Rozszerzenie enuma notificationtype (autogenerate nie wykrywa zmian wartości enuma).
    for value in NEW_NOTIFICATION_TYPES:
        op.execute(f"ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_recipient_snapshots',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.add_column(
        'task_subscriptions',
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_subscriptions', 'created_at')
    op.drop_table('task_recipient_snapshots')
    # ### end Alembic commands ###
    # Uwaga: PostgreSQL nie wspiera usuwania wartości z enuma — wartości
    # notificationtype pozostają po downgrade (świadomie pominięte).
